# Generated by Django 2.0.6 on 2018-06-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='pub_date',
        ),
    ]
